# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Visual Studio Professional Subscription(ec74a712-3898-4d3b-b156-b40ffb015c2f)'
    KeyVaultName: 'keyvault-test-00002'
    SecretsFilter: '*'
    RunAsPreJob: false