# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'sp-keyvault'
    KeyVaultName: 'keyvault-test-00001'
    SecretsFilter: '*'
    RunAsPreJob: false
- task: CmdLine@2
  displayName: "Use Key-Vault Secret"
  inputs:
    script: |
      echo 'SQLPassword:'$(SQLPassword)

